### ISSUE TITLE
Remove the `vendor` dir and use the modules in three.js and in NPM.

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe-core#720]

**Comment by RSpace** [comment]
This is breaking stuff for me in my projects where I have `"aframe-core": "git://github.com/aframevr/aframe-core.git#dev"` as a dependency in `package.json`, because webpack can't find the files on given paths.

To get it to work, I have to manually `npm install three-js` and then I have to change the paths to look like this:

```
require('../../three-dev/examples/js/loaders/OBJLoader');  // THREE.OBJLoader
require('../../three-dev/examples/js/loaders/ColladaLoader');  // THREE.ColladaLoader
require('../lib/vendor/Raycaster');  // THREE.Raycaster
require('../../three-dev/examples/js/controls/VRControls');  // THREE.VRControls
require('../../three-dev/examples/js/effects/VREffect');  // THREE.VREffect
```

Was this really ready to be merged?

**Comment by ngokevin** [comment]
We will move to having npm point to a pre-built version so people don't have to configure aframe build themselves. You can point npm to an earlier commit, but `dev` branch may have breaking changes time to time.

**Comment by cvan** [comment]
yeah, sorry about that. see #699 for more info.
